package com.gc.sdcmanager.model;

import com.gc.sdcmanager.model.base.BaseHgaccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Hgaccount extends BaseHgaccount<Hgaccount> {
	public static final Hgaccount dao = new Hgaccount();
}
