package com.gc.sdcmanager.model;

import com.gc.sdcmanager.model.base.BaseHgurl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Hgurl extends BaseHgurl<Hgurl> {
	public static final Hgurl dao = new Hgurl();
}
