package com.gc.sdcmanager.model;

import com.gc.sdcmanager.model.base.BaseSportsEvents;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SportsEvents extends BaseSportsEvents<SportsEvents> {
	public static final SportsEvents dao = new SportsEvents();
}
